-- ISO 3166-1 seed data: 249 officially assigned countries and territories
-- Generated for PostgreSQL table PUBLIC.ISO_COUNTRY.
-- RISK_RATING is deliberately set to UNRATED; replace it with your organization’s
-- approved jurisdiction-risk methodology before using it for compliance decisions.

BEGIN;

-- Optional for a full reload:
TRUNCATE TABLE PUBLIC.ISO_COUNTRY RESTART IDENTITY;

INSERT INTO PUBLIC.ISO_COUNTRY
(
    ISO_NAME,
    ISO_NUMERIC_CODE,
    ISO_2_CODE,
    ISO_3_CODE,
    PREFERRED_NAME,
    ALTERNATIVE_NAMES,
    RISK_RATING,
    IS_ENABLED
)
VALUES
    ('Afghanistan', 4, 'AF', 'AFG', 'Afghanistan', 'Islamic Republic of Afghanistan, AF, AFG', 'UNRATED', TRUE),
    ('Albania', 8, 'AL', 'ALB', 'Albania', 'Republic of Albania, AL, ALB', 'UNRATED', TRUE),
    ('Algeria', 12, 'DZ', 'DZA', 'Algeria', 'People''s Democratic Republic of Algeria, DZ, DZA', 'UNRATED', TRUE),
    ('American Samoa', 16, 'AS', 'ASM', 'American Samoa', 'AS, ASM', 'UNRATED', TRUE),
    ('Andorra', 20, 'AD', 'AND', 'Andorra', 'Principality of Andorra, AD, AND', 'UNRATED', TRUE),
    ('Angola', 24, 'AO', 'AGO', 'Angola', 'Republic of Angola, AO, AGO', 'UNRATED', TRUE),
    ('Anguilla', 660, 'AI', 'AIA', 'Anguilla', 'AI, AIA', 'UNRATED', TRUE),
    ('Antarctica', 10, 'AQ', 'ATA', 'Antarctica', 'AQ, ATA', 'UNRATED', TRUE),
    ('Antigua and Barbuda', 28, 'AG', 'ATG', 'Antigua and Barbuda', 'AG, ATG', 'UNRATED', TRUE),
    ('Argentina', 32, 'AR', 'ARG', 'Argentina', 'Argentine Republic, AR, ARG', 'UNRATED', TRUE),
    ('Armenia', 51, 'AM', 'ARM', 'Armenia', 'Republic of Armenia, AM, ARM', 'UNRATED', TRUE),
    ('Aruba', 533, 'AW', 'ABW', 'Aruba', 'AW, ABW', 'UNRATED', TRUE),
    ('Australia', 36, 'AU', 'AUS', 'Australia', 'AU, AUS', 'UNRATED', TRUE),
    ('Austria', 40, 'AT', 'AUT', 'Austria', 'Republic of Austria, AT, AUT', 'UNRATED', TRUE),
    ('Azerbaijan', 31, 'AZ', 'AZE', 'Azerbaijan', 'Republic of Azerbaijan, AZ, AZE', 'UNRATED', TRUE),
    ('Bahamas', 44, 'BS', 'BHS', 'Bahamas', 'Commonwealth of the Bahamas, BS, BHS', 'UNRATED', TRUE),
    ('Bahrain', 48, 'BH', 'BHR', 'Bahrain', 'Kingdom of Bahrain, BH, BHR', 'UNRATED', TRUE),
    ('Bangladesh', 50, 'BD', 'BGD', 'Bangladesh', 'People''s Republic of Bangladesh, BD, BGD', 'UNRATED', TRUE),
    ('Barbados', 52, 'BB', 'BRB', 'Barbados', 'BB, BRB', 'UNRATED', TRUE),
    ('Belarus', 112, 'BY', 'BLR', 'Belarus', 'Republic of Belarus, BY, BLR', 'UNRATED', TRUE),
    ('Belgium', 56, 'BE', 'BEL', 'Belgium', 'Kingdom of Belgium, BE, BEL', 'UNRATED', TRUE),
    ('Belize', 84, 'BZ', 'BLZ', 'Belize', 'BZ, BLZ', 'UNRATED', TRUE),
    ('Benin', 204, 'BJ', 'BEN', 'Benin', 'Republic of Benin, BJ, BEN', 'UNRATED', TRUE),
    ('Bermuda', 60, 'BM', 'BMU', 'Bermuda', 'BM, BMU', 'UNRATED', TRUE),
    ('Bhutan', 64, 'BT', 'BTN', 'Bhutan', 'Kingdom of Bhutan, BT, BTN', 'UNRATED', TRUE),
    ('Bolivia, Plurinational State of', 68, 'BO', 'BOL', 'Bolivia', 'Plurinational State of Bolivia, BO, BOL', 'UNRATED', TRUE),
    ('Bonaire, Sint Eustatius and Saba', 535, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'BQ, BES', 'UNRATED', TRUE),
    ('Bosnia and Herzegovina', 70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Republic of Bosnia and Herzegovina, BA, BIH', 'UNRATED', TRUE),
    ('Botswana', 72, 'BW', 'BWA', 'Botswana', 'Republic of Botswana, BW, BWA', 'UNRATED', TRUE),
    ('Bouvet Island', 74, 'BV', 'BVT', 'Bouvet Island', 'BV, BVT', 'UNRATED', TRUE),
    ('Brazil', 76, 'BR', 'BRA', 'Brazil', 'Federative Republic of Brazil, BR, BRA', 'UNRATED', TRUE),
    ('British Indian Ocean Territory', 86, 'IO', 'IOT', 'British Indian Ocean Territory', 'IO, IOT', 'UNRATED', TRUE),
    ('Brunei Darussalam', 96, 'BN', 'BRN', 'Brunei Darussalam', 'BN, BRN', 'UNRATED', TRUE),
    ('Bulgaria', 100, 'BG', 'BGR', 'Bulgaria', 'Republic of Bulgaria, BG, BGR', 'UNRATED', TRUE),
    ('Burkina Faso', 854, 'BF', 'BFA', 'Burkina Faso', 'BF, BFA', 'UNRATED', TRUE),
    ('Burundi', 108, 'BI', 'BDI', 'Burundi', 'Republic of Burundi, BI, BDI', 'UNRATED', TRUE),
    ('Cabo Verde', 132, 'CV', 'CPV', 'Cabo Verde', 'Republic of Cabo Verde, CV, CPV', 'UNRATED', TRUE),
    ('Cambodia', 116, 'KH', 'KHM', 'Cambodia', 'Kingdom of Cambodia, KH, KHM', 'UNRATED', TRUE),
    ('Cameroon', 120, 'CM', 'CMR', 'Cameroon', 'Republic of Cameroon, CM, CMR', 'UNRATED', TRUE),
    ('Canada', 124, 'CA', 'CAN', 'Canada', 'CA, CAN', 'UNRATED', TRUE),
    ('Cayman Islands', 136, 'KY', 'CYM', 'Cayman Islands', 'KY, CYM', 'UNRATED', TRUE),
    ('Central African Republic', 140, 'CF', 'CAF', 'Central African Republic', 'CF, CAF', 'UNRATED', TRUE),
    ('Chad', 148, 'TD', 'TCD', 'Chad', 'Republic of Chad, TD, TCD', 'UNRATED', TRUE),
    ('Chile', 152, 'CL', 'CHL', 'Chile', 'Republic of Chile, CL, CHL', 'UNRATED', TRUE),
    ('China', 156, 'CN', 'CHN', 'China', 'People''s Republic of China, CN, CHN', 'UNRATED', TRUE),
    ('Christmas Island', 162, 'CX', 'CXR', 'Christmas Island', 'CX, CXR', 'UNRATED', TRUE),
    ('Cocos (Keeling) Islands', 166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'CC, CCK', 'UNRATED', TRUE),
    ('Colombia', 170, 'CO', 'COL', 'Colombia', 'Republic of Colombia, CO, COL', 'UNRATED', TRUE),
    ('Comoros', 174, 'KM', 'COM', 'Comoros', 'Union of the Comoros, KM, COM', 'UNRATED', TRUE),
    ('Congo', 178, 'CG', 'COG', 'Congo', 'Republic of the Congo, CG, COG', 'UNRATED', TRUE),
    ('Congo, The Democratic Republic of the', 180, 'CD', 'COD', 'Congo, The Democratic Republic of the', 'CD, COD', 'UNRATED', TRUE),
    ('Cook Islands', 184, 'CK', 'COK', 'Cook Islands', 'CK, COK', 'UNRATED', TRUE),
    ('Costa Rica', 188, 'CR', 'CRI', 'Costa Rica', 'Republic of Costa Rica, CR, CRI', 'UNRATED', TRUE),
    ('Croatia', 191, 'HR', 'HRV', 'Croatia', 'Republic of Croatia, HR, HRV', 'UNRATED', TRUE),
    ('Cuba', 192, 'CU', 'CUB', 'Cuba', 'Republic of Cuba, CU, CUB', 'UNRATED', TRUE),
    ('Curaçao', 531, 'CW', 'CUW', 'Curaçao', 'CW, CUW', 'UNRATED', TRUE),
    ('Cyprus', 196, 'CY', 'CYP', 'Cyprus', 'Republic of Cyprus, CY, CYP', 'UNRATED', TRUE),
    ('Czechia', 203, 'CZ', 'CZE', 'Czechia', 'Czech Republic, CZ, CZE', 'UNRATED', TRUE),
    ('Côte d''Ivoire', 384, 'CI', 'CIV', 'Côte d''Ivoire', 'Republic of Côte d''Ivoire, CI, CIV', 'UNRATED', TRUE),
    ('Denmark', 208, 'DK', 'DNK', 'Denmark', 'Kingdom of Denmark, DK, DNK', 'UNRATED', TRUE),
    ('Djibouti', 262, 'DJ', 'DJI', 'Djibouti', 'Republic of Djibouti, DJ, DJI', 'UNRATED', TRUE),
    ('Dominica', 212, 'DM', 'DMA', 'Dominica', 'Commonwealth of Dominica, DM, DMA', 'UNRATED', TRUE),
    ('Dominican Republic', 214, 'DO', 'DOM', 'Dominican Republic', 'DO, DOM', 'UNRATED', TRUE),
    ('Ecuador', 218, 'EC', 'ECU', 'Ecuador', 'Republic of Ecuador, EC, ECU', 'UNRATED', TRUE),
    ('Egypt', 818, 'EG', 'EGY', 'Egypt', 'Arab Republic of Egypt, EG, EGY', 'UNRATED', TRUE),
    ('El Salvador', 222, 'SV', 'SLV', 'El Salvador', 'Republic of El Salvador, SV, SLV', 'UNRATED', TRUE),
    ('Equatorial Guinea', 226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Republic of Equatorial Guinea, GQ, GNQ', 'UNRATED', TRUE),
    ('Eritrea', 232, 'ER', 'ERI', 'Eritrea', 'the State of Eritrea, ER, ERI', 'UNRATED', TRUE),
    ('Estonia', 233, 'EE', 'EST', 'Estonia', 'Republic of Estonia, EE, EST', 'UNRATED', TRUE),
    ('Eswatini', 748, 'SZ', 'SWZ', 'Eswatini', 'Kingdom of Eswatini, SZ, SWZ', 'UNRATED', TRUE),
    ('Ethiopia', 231, 'ET', 'ETH', 'Ethiopia', 'Federal Democratic Republic of Ethiopia, ET, ETH', 'UNRATED', TRUE),
    ('Falkland Islands (Malvinas)', 238, 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'FK, FLK', 'UNRATED', TRUE),
    ('Faroe Islands', 234, 'FO', 'FRO', 'Faroe Islands', 'FO, FRO', 'UNRATED', TRUE),
    ('Fiji', 242, 'FJ', 'FJI', 'Fiji', 'Republic of Fiji, FJ, FJI', 'UNRATED', TRUE),
    ('Finland', 246, 'FI', 'FIN', 'Finland', 'Republic of Finland, FI, FIN', 'UNRATED', TRUE),
    ('France', 250, 'FR', 'FRA', 'France', 'French Republic, FR, FRA', 'UNRATED', TRUE),
    ('French Guiana', 254, 'GF', 'GUF', 'French Guiana', 'GF, GUF', 'UNRATED', TRUE),
    ('French Polynesia', 258, 'PF', 'PYF', 'French Polynesia', 'PF, PYF', 'UNRATED', TRUE),
    ('French Southern Territories', 260, 'TF', 'ATF', 'French Southern Territories', 'TF, ATF', 'UNRATED', TRUE),
    ('Gabon', 266, 'GA', 'GAB', 'Gabon', 'Gabonese Republic, GA, GAB', 'UNRATED', TRUE),
    ('Gambia', 270, 'GM', 'GMB', 'Gambia', 'Republic of the Gambia, GM, GMB', 'UNRATED', TRUE),
    ('Georgia', 268, 'GE', 'GEO', 'Georgia', 'GE, GEO', 'UNRATED', TRUE),
    ('Germany', 276, 'DE', 'DEU', 'Germany', 'Federal Republic of Germany, DE, DEU', 'UNRATED', TRUE),
    ('Ghana', 288, 'GH', 'GHA', 'Ghana', 'Republic of Ghana, GH, GHA', 'UNRATED', TRUE),
    ('Gibraltar', 292, 'GI', 'GIB', 'Gibraltar', 'GI, GIB', 'UNRATED', TRUE),
    ('Greece', 300, 'GR', 'GRC', 'Greece', 'Hellenic Republic, GR, GRC', 'UNRATED', TRUE),
    ('Greenland', 304, 'GL', 'GRL', 'Greenland', 'GL, GRL', 'UNRATED', TRUE),
    ('Grenada', 308, 'GD', 'GRD', 'Grenada', 'GD, GRD', 'UNRATED', TRUE),
    ('Guadeloupe', 312, 'GP', 'GLP', 'Guadeloupe', 'GP, GLP', 'UNRATED', TRUE),
    ('Guam', 316, 'GU', 'GUM', 'Guam', 'GU, GUM', 'UNRATED', TRUE),
    ('Guatemala', 320, 'GT', 'GTM', 'Guatemala', 'Republic of Guatemala, GT, GTM', 'UNRATED', TRUE),
    ('Guernsey', 831, 'GG', 'GGY', 'Guernsey', 'GG, GGY', 'UNRATED', TRUE),
    ('Guinea', 324, 'GN', 'GIN', 'Guinea', 'Republic of Guinea, GN, GIN', 'UNRATED', TRUE),
    ('Guinea-Bissau', 624, 'GW', 'GNB', 'Guinea-Bissau', 'Republic of Guinea-Bissau, GW, GNB', 'UNRATED', TRUE),
    ('Guyana', 328, 'GY', 'GUY', 'Guyana', 'Republic of Guyana, GY, GUY', 'UNRATED', TRUE),
    ('Haiti', 332, 'HT', 'HTI', 'Haiti', 'Republic of Haiti, HT, HTI', 'UNRATED', TRUE),
    ('Heard Island and McDonald Islands', 334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'HM, HMD', 'UNRATED', TRUE),
    ('Holy See (Vatican City State)', 336, 'VA', 'VAT', 'Holy See (Vatican City State)', 'VA, VAT', 'UNRATED', TRUE),
    ('Honduras', 340, 'HN', 'HND', 'Honduras', 'Republic of Honduras, HN, HND', 'UNRATED', TRUE),
    ('Hong Kong', 344, 'HK', 'HKG', 'Hong Kong', 'Hong Kong Special Administrative Region of China, HK, HKG', 'UNRATED', TRUE),
    ('Hungary', 348, 'HU', 'HUN', 'Hungary', 'HU, HUN', 'UNRATED', TRUE),
    ('Iceland', 352, 'IS', 'ISL', 'Iceland', 'Republic of Iceland, IS, ISL', 'UNRATED', TRUE),
    ('India', 356, 'IN', 'IND', 'India', 'Republic of India, IN, IND', 'UNRATED', TRUE),
    ('Indonesia', 360, 'ID', 'IDN', 'Indonesia', 'Republic of Indonesia, ID, IDN', 'UNRATED', TRUE),
    ('Iran, Islamic Republic of', 364, 'IR', 'IRN', 'Iran', 'Islamic Republic of Iran, IR, IRN', 'UNRATED', TRUE),
    ('Iraq', 368, 'IQ', 'IRQ', 'Iraq', 'Republic of Iraq, IQ, IRQ', 'UNRATED', TRUE),
    ('Ireland', 372, 'IE', 'IRL', 'Ireland', 'IE, IRL', 'UNRATED', TRUE),
    ('Isle of Man', 833, 'IM', 'IMN', 'Isle of Man', 'IM, IMN', 'UNRATED', TRUE),
    ('Israel', 376, 'IL', 'ISR', 'Israel', 'State of Israel, IL, ISR', 'UNRATED', TRUE),
    ('Italy', 380, 'IT', 'ITA', 'Italy', 'Italian Republic, IT, ITA', 'UNRATED', TRUE),
    ('Jamaica', 388, 'JM', 'JAM', 'Jamaica', 'JM, JAM', 'UNRATED', TRUE),
    ('Japan', 392, 'JP', 'JPN', 'Japan', 'JP, JPN', 'UNRATED', TRUE),
    ('Jersey', 832, 'JE', 'JEY', 'Jersey', 'JE, JEY', 'UNRATED', TRUE),
    ('Jordan', 400, 'JO', 'JOR', 'Jordan', 'Hashemite Kingdom of Jordan, JO, JOR', 'UNRATED', TRUE),
    ('Kazakhstan', 398, 'KZ', 'KAZ', 'Kazakhstan', 'Republic of Kazakhstan, KZ, KAZ', 'UNRATED', TRUE),
    ('Kenya', 404, 'KE', 'KEN', 'Kenya', 'Republic of Kenya, KE, KEN', 'UNRATED', TRUE),
    ('Kiribati', 296, 'KI', 'KIR', 'Kiribati', 'Republic of Kiribati, KI, KIR', 'UNRATED', TRUE),
    ('Korea, Democratic People''s Republic of', 408, 'KP', 'PRK', 'North Korea', 'Democratic People''s Republic of Korea, KP, PRK', 'UNRATED', TRUE),
    ('Korea, Republic of', 410, 'KR', 'KOR', 'South Korea', 'KR, KOR', 'UNRATED', TRUE),
    ('Kuwait', 414, 'KW', 'KWT', 'Kuwait', 'State of Kuwait, KW, KWT', 'UNRATED', TRUE),
    ('Kyrgyzstan', 417, 'KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyz Republic, KG, KGZ', 'UNRATED', TRUE),
    ('Lao People''s Democratic Republic', 418, 'LA', 'LAO', 'Laos', 'LA, LAO', 'UNRATED', TRUE),
    ('Latvia', 428, 'LV', 'LVA', 'Latvia', 'Republic of Latvia, LV, LVA', 'UNRATED', TRUE),
    ('Lebanon', 422, 'LB', 'LBN', 'Lebanon', 'Lebanese Republic, LB, LBN', 'UNRATED', TRUE),
    ('Lesotho', 426, 'LS', 'LSO', 'Lesotho', 'Kingdom of Lesotho, LS, LSO', 'UNRATED', TRUE),
    ('Liberia', 430, 'LR', 'LBR', 'Liberia', 'Republic of Liberia, LR, LBR', 'UNRATED', TRUE),
    ('Libya', 434, 'LY', 'LBY', 'Libya', 'LY, LBY', 'UNRATED', TRUE),
    ('Liechtenstein', 438, 'LI', 'LIE', 'Liechtenstein', 'Principality of Liechtenstein, LI, LIE', 'UNRATED', TRUE),
    ('Lithuania', 440, 'LT', 'LTU', 'Lithuania', 'Republic of Lithuania, LT, LTU', 'UNRATED', TRUE),
    ('Luxembourg', 442, 'LU', 'LUX', 'Luxembourg', 'Grand Duchy of Luxembourg, LU, LUX', 'UNRATED', TRUE),
    ('Macao', 446, 'MO', 'MAC', 'Macao', 'Macao Special Administrative Region of China, MO, MAC', 'UNRATED', TRUE),
    ('Madagascar', 450, 'MG', 'MDG', 'Madagascar', 'Republic of Madagascar, MG, MDG', 'UNRATED', TRUE),
    ('Malawi', 454, 'MW', 'MWI', 'Malawi', 'Republic of Malawi, MW, MWI', 'UNRATED', TRUE),
    ('Malaysia', 458, 'MY', 'MYS', 'Malaysia', 'MY, MYS', 'UNRATED', TRUE),
    ('Maldives', 462, 'MV', 'MDV', 'Maldives', 'Republic of Maldives, MV, MDV', 'UNRATED', TRUE),
    ('Mali', 466, 'ML', 'MLI', 'Mali', 'Republic of Mali, ML, MLI', 'UNRATED', TRUE),
    ('Malta', 470, 'MT', 'MLT', 'Malta', 'Republic of Malta, MT, MLT', 'UNRATED', TRUE),
    ('Marshall Islands', 584, 'MH', 'MHL', 'Marshall Islands', 'Republic of the Marshall Islands, MH, MHL', 'UNRATED', TRUE),
    ('Martinique', 474, 'MQ', 'MTQ', 'Martinique', 'MQ, MTQ', 'UNRATED', TRUE),
    ('Mauritania', 478, 'MR', 'MRT', 'Mauritania', 'Islamic Republic of Mauritania, MR, MRT', 'UNRATED', TRUE),
    ('Mauritius', 480, 'MU', 'MUS', 'Mauritius', 'Republic of Mauritius, MU, MUS', 'UNRATED', TRUE),
    ('Mayotte', 175, 'YT', 'MYT', 'Mayotte', 'YT, MYT', 'UNRATED', TRUE),
    ('Mexico', 484, 'MX', 'MEX', 'Mexico', 'United Mexican States, MX, MEX', 'UNRATED', TRUE),
    ('Micronesia, Federated States of', 583, 'FM', 'FSM', 'Micronesia, Federated States of', 'Federated States of Micronesia, FM, FSM', 'UNRATED', TRUE),
    ('Moldova, Republic of', 498, 'MD', 'MDA', 'Moldova', 'Republic of Moldova, MD, MDA', 'UNRATED', TRUE),
    ('Monaco', 492, 'MC', 'MCO', 'Monaco', 'Principality of Monaco, MC, MCO', 'UNRATED', TRUE),
    ('Mongolia', 496, 'MN', 'MNG', 'Mongolia', 'MN, MNG', 'UNRATED', TRUE),
    ('Montenegro', 499, 'ME', 'MNE', 'Montenegro', 'ME, MNE', 'UNRATED', TRUE),
    ('Montserrat', 500, 'MS', 'MSR', 'Montserrat', 'MS, MSR', 'UNRATED', TRUE),
    ('Morocco', 504, 'MA', 'MAR', 'Morocco', 'Kingdom of Morocco, MA, MAR', 'UNRATED', TRUE),
    ('Mozambique', 508, 'MZ', 'MOZ', 'Mozambique', 'Republic of Mozambique, MZ, MOZ', 'UNRATED', TRUE),
    ('Myanmar', 104, 'MM', 'MMR', 'Myanmar', 'Republic of Myanmar, MM, MMR', 'UNRATED', TRUE),
    ('Namibia', 516, 'NA', 'NAM', 'Namibia', 'Republic of Namibia, NA, NAM', 'UNRATED', TRUE),
    ('Nauru', 520, 'NR', 'NRU', 'Nauru', 'Republic of Nauru, NR, NRU', 'UNRATED', TRUE),
    ('Nepal', 524, 'NP', 'NPL', 'Nepal', 'Federal Democratic Republic of Nepal, NP, NPL', 'UNRATED', TRUE),
    ('Netherlands', 528, 'NL', 'NLD', 'Netherlands', 'Kingdom of the Netherlands, NL, NLD', 'UNRATED', TRUE),
    ('New Caledonia', 540, 'NC', 'NCL', 'New Caledonia', 'NC, NCL', 'UNRATED', TRUE),
    ('New Zealand', 554, 'NZ', 'NZL', 'New Zealand', 'NZ, NZL', 'UNRATED', TRUE),
    ('Nicaragua', 558, 'NI', 'NIC', 'Nicaragua', 'Republic of Nicaragua, NI, NIC', 'UNRATED', TRUE),
    ('Niger', 562, 'NE', 'NER', 'Niger', 'Republic of the Niger, NE, NER', 'UNRATED', TRUE),
    ('Nigeria', 566, 'NG', 'NGA', 'Nigeria', 'Federal Republic of Nigeria, NG, NGA', 'UNRATED', TRUE),
    ('Niue', 570, 'NU', 'NIU', 'Niue', 'NU, NIU', 'UNRATED', TRUE),
    ('Norfolk Island', 574, 'NF', 'NFK', 'Norfolk Island', 'NF, NFK', 'UNRATED', TRUE),
    ('North Macedonia', 807, 'MK', 'MKD', 'North Macedonia', 'Republic of North Macedonia, MK, MKD', 'UNRATED', TRUE),
    ('Northern Mariana Islands', 580, 'MP', 'MNP', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands, MP, MNP', 'UNRATED', TRUE),
    ('Norway', 578, 'NO', 'NOR', 'Norway', 'Kingdom of Norway, NO, NOR', 'UNRATED', TRUE),
    ('Oman', 512, 'OM', 'OMN', 'Oman', 'Sultanate of Oman, OM, OMN', 'UNRATED', TRUE),
    ('Pakistan', 586, 'PK', 'PAK', 'Pakistan', 'Islamic Republic of Pakistan, PK, PAK', 'UNRATED', TRUE),
    ('Palau', 585, 'PW', 'PLW', 'Palau', 'Republic of Palau, PW, PLW', 'UNRATED', TRUE),
    ('Palestine, State of', 275, 'PS', 'PSE', 'Palestine, State of', 'the State of Palestine, PS, PSE', 'UNRATED', TRUE),
    ('Panama', 591, 'PA', 'PAN', 'Panama', 'Republic of Panama, PA, PAN', 'UNRATED', TRUE),
    ('Papua New Guinea', 598, 'PG', 'PNG', 'Papua New Guinea', 'Independent State of Papua New Guinea, PG, PNG', 'UNRATED', TRUE),
    ('Paraguay', 600, 'PY', 'PRY', 'Paraguay', 'Republic of Paraguay, PY, PRY', 'UNRATED', TRUE),
    ('Peru', 604, 'PE', 'PER', 'Peru', 'Republic of Peru, PE, PER', 'UNRATED', TRUE),
    ('Philippines', 608, 'PH', 'PHL', 'Philippines', 'Republic of the Philippines, PH, PHL', 'UNRATED', TRUE),
    ('Pitcairn', 612, 'PN', 'PCN', 'Pitcairn', 'PN, PCN', 'UNRATED', TRUE),
    ('Poland', 616, 'PL', 'POL', 'Poland', 'Republic of Poland, PL, POL', 'UNRATED', TRUE),
    ('Portugal', 620, 'PT', 'PRT', 'Portugal', 'Portuguese Republic, PT, PRT', 'UNRATED', TRUE),
    ('Puerto Rico', 630, 'PR', 'PRI', 'Puerto Rico', 'PR, PRI', 'UNRATED', TRUE),
    ('Qatar', 634, 'QA', 'QAT', 'Qatar', 'State of Qatar, QA, QAT', 'UNRATED', TRUE),
    ('Romania', 642, 'RO', 'ROU', 'Romania', 'RO, ROU', 'UNRATED', TRUE),
    ('Russian Federation', 643, 'RU', 'RUS', 'Russian Federation', 'RU, RUS', 'UNRATED', TRUE),
    ('Rwanda', 646, 'RW', 'RWA', 'Rwanda', 'Rwandese Republic, RW, RWA', 'UNRATED', TRUE),
    ('Réunion', 638, 'RE', 'REU', 'Réunion', 'RE, REU', 'UNRATED', TRUE),
    ('Saint Barthélemy', 652, 'BL', 'BLM', 'Saint Barthélemy', 'BL, BLM', 'UNRATED', TRUE),
    ('Saint Helena, Ascension and Tristan da Cunha', 654, 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'SH, SHN', 'UNRATED', TRUE),
    ('Saint Kitts and Nevis', 659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'KN, KNA', 'UNRATED', TRUE),
    ('Saint Lucia', 662, 'LC', 'LCA', 'Saint Lucia', 'LC, LCA', 'UNRATED', TRUE),
    ('Saint Martin (French part)', 663, 'MF', 'MAF', 'Saint Martin (French part)', 'MF, MAF', 'UNRATED', TRUE),
    ('Saint Pierre and Miquelon', 666, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'PM, SPM', 'UNRATED', TRUE),
    ('Saint Vincent and the Grenadines', 670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'VC, VCT', 'UNRATED', TRUE),
    ('Samoa', 882, 'WS', 'WSM', 'Samoa', 'Independent State of Samoa, WS, WSM', 'UNRATED', TRUE),
    ('San Marino', 674, 'SM', 'SMR', 'San Marino', 'Republic of San Marino, SM, SMR', 'UNRATED', TRUE),
    ('Sao Tome and Principe', 678, 'ST', 'STP', 'Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe, ST, STP', 'UNRATED', TRUE),
    ('Saudi Arabia', 682, 'SA', 'SAU', 'Saudi Arabia', 'Kingdom of Saudi Arabia, SA, SAU', 'UNRATED', TRUE),
    ('Senegal', 686, 'SN', 'SEN', 'Senegal', 'Republic of Senegal, SN, SEN', 'UNRATED', TRUE),
    ('Serbia', 688, 'RS', 'SRB', 'Serbia', 'Republic of Serbia, RS, SRB', 'UNRATED', TRUE),
    ('Seychelles', 690, 'SC', 'SYC', 'Seychelles', 'Republic of Seychelles, SC, SYC', 'UNRATED', TRUE),
    ('Sierra Leone', 694, 'SL', 'SLE', 'Sierra Leone', 'Republic of Sierra Leone, SL, SLE', 'UNRATED', TRUE),
    ('Singapore', 702, 'SG', 'SGP', 'Singapore', 'Republic of Singapore, SG, SGP', 'UNRATED', TRUE),
    ('Sint Maarten (Dutch part)', 534, 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'SX, SXM', 'UNRATED', TRUE),
    ('Slovakia', 703, 'SK', 'SVK', 'Slovakia', 'Slovak Republic, SK, SVK', 'UNRATED', TRUE),
    ('Slovenia', 705, 'SI', 'SVN', 'Slovenia', 'Republic of Slovenia, SI, SVN', 'UNRATED', TRUE),
    ('Solomon Islands', 90, 'SB', 'SLB', 'Solomon Islands', 'SB, SLB', 'UNRATED', TRUE),
    ('Somalia', 706, 'SO', 'SOM', 'Somalia', 'Federal Republic of Somalia, SO, SOM', 'UNRATED', TRUE),
    ('South Africa', 710, 'ZA', 'ZAF', 'South Africa', 'Republic of South Africa, ZA, ZAF', 'UNRATED', TRUE),
    ('South Georgia and the South Sandwich Islands', 239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'GS, SGS', 'UNRATED', TRUE),
    ('South Sudan', 728, 'SS', 'SSD', 'South Sudan', 'Republic of South Sudan, SS, SSD', 'UNRATED', TRUE),
    ('Spain', 724, 'ES', 'ESP', 'Spain', 'Kingdom of Spain, ES, ESP', 'UNRATED', TRUE),
    ('Sri Lanka', 144, 'LK', 'LKA', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka, LK, LKA', 'UNRATED', TRUE),
    ('Sudan', 729, 'SD', 'SDN', 'Sudan', 'Republic of the Sudan, SD, SDN', 'UNRATED', TRUE),
    ('Suriname', 740, 'SR', 'SUR', 'Suriname', 'Republic of Suriname, SR, SUR', 'UNRATED', TRUE),
    ('Svalbard and Jan Mayen', 744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'SJ, SJM', 'UNRATED', TRUE),
    ('Sweden', 752, 'SE', 'SWE', 'Sweden', 'Kingdom of Sweden, SE, SWE', 'UNRATED', TRUE),
    ('Switzerland', 756, 'CH', 'CHE', 'Switzerland', 'Swiss Confederation, CH, CHE', 'UNRATED', TRUE),
    ('Syrian Arab Republic', 760, 'SY', 'SYR', 'Syria', 'SY, SYR', 'UNRATED', TRUE),
    ('Taiwan, Province of China', 158, 'TW', 'TWN', 'Taiwan', 'TW, TWN', 'UNRATED', TRUE),
    ('Tajikistan', 762, 'TJ', 'TJK', 'Tajikistan', 'Republic of Tajikistan, TJ, TJK', 'UNRATED', TRUE),
    ('Tanzania, United Republic of', 834, 'TZ', 'TZA', 'Tanzania', 'United Republic of Tanzania, TZ, TZA', 'UNRATED', TRUE),
    ('Thailand', 764, 'TH', 'THA', 'Thailand', 'Kingdom of Thailand, TH, THA', 'UNRATED', TRUE),
    ('Timor-Leste', 626, 'TL', 'TLS', 'Timor-Leste', 'Democratic Republic of Timor-Leste, TL, TLS', 'UNRATED', TRUE),
    ('Togo', 768, 'TG', 'TGO', 'Togo', 'Togolese Republic, TG, TGO', 'UNRATED', TRUE),
    ('Tokelau', 772, 'TK', 'TKL', 'Tokelau', 'TK, TKL', 'UNRATED', TRUE),
    ('Tonga', 776, 'TO', 'TON', 'Tonga', 'Kingdom of Tonga, TO, TON', 'UNRATED', TRUE),
    ('Trinidad and Tobago', 780, 'TT', 'TTO', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago, TT, TTO', 'UNRATED', TRUE),
    ('Tunisia', 788, 'TN', 'TUN', 'Tunisia', 'Republic of Tunisia, TN, TUN', 'UNRATED', TRUE),
    ('Turkmenistan', 795, 'TM', 'TKM', 'Turkmenistan', 'TM, TKM', 'UNRATED', TRUE),
    ('Turks and Caicos Islands', 796, 'TC', 'TCA', 'Turks and Caicos Islands', 'TC, TCA', 'UNRATED', TRUE),
    ('Tuvalu', 798, 'TV', 'TUV', 'Tuvalu', 'TV, TUV', 'UNRATED', TRUE),
    ('Türkiye', 792, 'TR', 'TUR', 'Türkiye', 'Republic of Türkiye, TR, TUR', 'UNRATED', TRUE),
    ('Uganda', 800, 'UG', 'UGA', 'Uganda', 'Republic of Uganda, UG, UGA', 'UNRATED', TRUE),
    ('Ukraine', 804, 'UA', 'UKR', 'Ukraine', 'UA, UKR', 'UNRATED', TRUE),
    ('United Arab Emirates', 784, 'AE', 'ARE', 'United Arab Emirates', 'AE, ARE', 'UNRATED', TRUE),
    ('United Kingdom', 826, 'GB', 'GBR', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland, GB, GBR', 'UNRATED', TRUE),
    ('United States', 840, 'US', 'USA', 'United States', 'United States of America, US, USA', 'UNRATED', TRUE),
    ('United States Minor Outlying Islands', 581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'UM, UMI', 'UNRATED', TRUE),
    ('Uruguay', 858, 'UY', 'URY', 'Uruguay', 'Eastern Republic of Uruguay, UY, URY', 'UNRATED', TRUE),
    ('Uzbekistan', 860, 'UZ', 'UZB', 'Uzbekistan', 'Republic of Uzbekistan, UZ, UZB', 'UNRATED', TRUE),
    ('Vanuatu', 548, 'VU', 'VUT', 'Vanuatu', 'Republic of Vanuatu, VU, VUT', 'UNRATED', TRUE),
    ('Venezuela, Bolivarian Republic of', 862, 'VE', 'VEN', 'Venezuela', 'Bolivarian Republic of Venezuela, VE, VEN', 'UNRATED', TRUE),
    ('Viet Nam', 704, 'VN', 'VNM', 'Vietnam', 'Socialist Republic of Viet Nam, VN, VNM', 'UNRATED', TRUE),
    ('Virgin Islands, British', 92, 'VG', 'VGB', 'Virgin Islands, British', 'British Virgin Islands, VG, VGB', 'UNRATED', TRUE),
    ('Virgin Islands, U.S.', 850, 'VI', 'VIR', 'Virgin Islands, U.S.', 'Virgin Islands of the United States, VI, VIR', 'UNRATED', TRUE),
    ('Wallis and Futuna', 876, 'WF', 'WLF', 'Wallis and Futuna', 'WF, WLF', 'UNRATED', TRUE),
    ('Western Sahara', 732, 'EH', 'ESH', 'Western Sahara', 'EH, ESH', 'UNRATED', TRUE),
    ('Yemen', 887, 'YE', 'YEM', 'Yemen', 'Republic of Yemen, YE, YEM', 'UNRATED', TRUE),
    ('Zambia', 894, 'ZM', 'ZMB', 'Zambia', 'Republic of Zambia, ZM, ZMB', 'UNRATED', TRUE),
    ('Zimbabwe', 716, 'ZW', 'ZWE', 'Zimbabwe', 'Republic of Zimbabwe, ZW, ZWE', 'UNRATED', TRUE),
    ('Åland Islands', 248, 'AX', 'ALA', 'Åland Islands', 'AX, ALA', 'UNRATED', TRUE);

COMMIT;
