-- ISO 4217 active currency and funds seed data
-- Code/name/numeric basis: ISO 4217 maintenance agency (SIX), List One
-- Currency symbols are display metadata and are not standardized by ISO 4217.
-- Generated 2026-08-01; one row per distinct active alphabetic code.

BEGIN;

TRUNCATE TABLE PUBLIC.ISO_CURRENCY RESTART IDENTITY;

INSERT INTO PUBLIC.ISO_CURRENCY
(
    ISO_NAME,
    ISO_NUMERIC_CODE,
    ISO_3_CODE,
    CURRENCY_SYMBOL,
    PREFERRED_NAME,
    ALTERNATIVE_NAMES,
    DECIMAL_PLACES,
    IS_ENABLED
)
VALUES
('UAE Dirham', 784, 'AED', 'AED', 'UAE Dirham', 'AED,UAE Dirham', 2, TRUE),
('Afghani', 971, 'AFN', 'AFN', 'Afghani', 'AFN,Afghani', 0, TRUE),
('Lek', 8, 'ALL', 'ALL', 'Lek', 'ALL,Lek', 0, TRUE),
('Armenian Dram', 51, 'AMD', 'AMD', 'Armenian Dram', 'AMD,Armenian Dram', 2, TRUE),
('Netherlands Antillean Guilder', 532, 'ANG', 'ANG', 'Netherlands Antillean Guilder', 'ANG,Netherlands Antillean Guilder', 2, TRUE),
('Kwanza', 973, 'AOA', 'AOA', 'Kwanza', 'AOA,Kwanza', 2, TRUE),
('Argentine Peso', 32, 'ARS', 'ARS', 'Argentine Peso', 'ARS,Argentine Peso', 2, TRUE),
('Australian Dollar', 36, 'AUD', 'A$', 'Australian Dollar', 'AUD,Australian Dollar', 2, TRUE),
('Aruban Florin', 533, 'AWG', 'AWG', 'Aruban Florin', 'AWG,Aruban Florin', 2, TRUE),
('Azerbaijan Manat', 944, 'AZN', 'AZN', 'Azerbaijan Manat', 'AZN,Azerbaijan Manat', 2, TRUE),
('Convertible Mark', 977, 'BAM', 'BAM', 'Convertible Mark', 'BAM,Convertible Mark', 2, TRUE),
('Barbados Dollar', 52, 'BBD', 'BBD', 'Barbados Dollar', 'BBD,Barbados Dollar', 2, TRUE),
('Taka', 50, 'BDT', 'BDT', 'Taka', 'BDT,Taka', 2, TRUE),
('Bulgarian Lev', 975, 'BGN', 'BGN', 'Bulgarian Lev', 'BGN,Bulgarian Lev', 2, TRUE),
('Bahraini Dinar', 48, 'BHD', 'BHD', 'Bahraini Dinar', 'BHD,Bahraini Dinar', 3, TRUE),
('Burundi Franc', 108, 'BIF', 'BIF', 'Burundi Franc', 'BIF,Burundi Franc', 0, TRUE),
('Bermudian Dollar', 60, 'BMD', 'BMD', 'Bermudian Dollar', 'BMD,Bermudian Dollar', 2, TRUE),
('Brunei Dollar', 96, 'BND', 'BND', 'Brunei Dollar', 'BND,Brunei Dollar', 2, TRUE),
('Boliviano', 68, 'BOB', 'BOB', 'Boliviano', 'BOB,Boliviano', 2, TRUE),
('Mvdol', 984, 'BOV', 'BOV', 'Mvdol', 'BOV,Mvdol', 2, TRUE),
('Brazilian Real', 986, 'BRL', 'R$', 'Brazilian Real', 'BRL,Brazilian Real', 2, TRUE),
('Bahamian Dollar', 44, 'BSD', 'BSD', 'Bahamian Dollar', 'BSD,Bahamian Dollar', 2, TRUE),
('Ngultrum', 64, 'BTN', 'BTN', 'Ngultrum', 'BTN,Ngultrum', 2, TRUE),
('Pula', 72, 'BWP', 'BWP', 'Pula', 'BWP,Pula', 2, TRUE),
('Belarusian Ruble', 933, 'BYN', 'BYN', 'Belarusian Ruble', 'BYN,Belarusian Ruble', 2, TRUE),
('Belize Dollar', 84, 'BZD', 'BZD', 'Belize Dollar', 'BZD,Belize Dollar', 2, TRUE),
('Canadian Dollar', 124, 'CAD', 'CA$', 'Canadian Dollar', 'CAD,Canadian Dollar', 2, TRUE),
('Congolese Franc', 976, 'CDF', 'CDF', 'Congolese Franc', 'CDF,Congolese Franc', 2, TRUE),
('WIR Euro', 947, 'CHE', 'CHE', 'WIR Euro', 'CHE,WIR Euro', 2, TRUE),
('Swiss Franc', 756, 'CHF', 'CHF', 'Swiss Franc', 'CHF,Swiss Franc', 2, TRUE),
('WIR Franc', 948, 'CHW', 'CHW', 'WIR Franc', 'CHW,WIR Franc', 2, TRUE),
('Unidad de Fomento', 990, 'CLF', 'CLF', 'Unidad de Fomento', 'CLF,Unidad de Fomento', 4, TRUE),
('Chilean Peso', 152, 'CLP', 'CLP', 'Chilean Peso', 'CLP,Chilean Peso', 0, TRUE),
('Yuan Renminbi', 156, 'CNY', 'CN¥', 'Yuan Renminbi', 'CNY,Yuan Renminbi', 2, TRUE),
('Colombian Peso', 170, 'COP', 'COP', 'Colombian Peso', 'COP,Colombian Peso', 2, TRUE),
('Unidad de Valor Real', 970, 'COU', 'COU', 'Unidad de Valor Real', 'COU,Unidad de Valor Real', 2, TRUE),
('Costa Rican Colon', 188, 'CRC', 'CRC', 'Costa Rican Colon', 'CRC,Costa Rican Colon', 2, TRUE),
('Peso Convertible', 931, 'CUC', 'CUC', 'Peso Convertible', 'CUC,Peso Convertible', 2, TRUE),
('Cuban Peso', 192, 'CUP', 'CUP', 'Cuban Peso', 'CUP,Cuban Peso', 2, TRUE),
('Cabo Verde Escudo', 132, 'CVE', 'CVE', 'Cabo Verde Escudo', 'CVE,Cabo Verde Escudo', 2, TRUE),
('Czech Koruna', 203, 'CZK', 'CZK', 'Czech Koruna', 'CZK,Czech Koruna', 2, TRUE),
('Djibouti Franc', 262, 'DJF', 'DJF', 'Djibouti Franc', 'DJF,Djibouti Franc', 0, TRUE),
('Danish Krone', 208, 'DKK', 'DKK', 'Danish Krone', 'DKK,Danish Krone', 2, TRUE),
('Dominican Peso', 214, 'DOP', 'DOP', 'Dominican Peso', 'DOP,Dominican Peso', 2, TRUE),
('Algerian Dinar', 12, 'DZD', 'DZD', 'Algerian Dinar', 'DZD,Algerian Dinar', 2, TRUE),
('Egyptian Pound', 818, 'EGP', 'EGP', 'Egyptian Pound', 'EGP,Egyptian Pound', 2, TRUE),
('Nakfa', 232, 'ERN', 'ERN', 'Nakfa', 'ERN,Nakfa', 2, TRUE),
('Ethiopian Birr', 230, 'ETB', 'ETB', 'Ethiopian Birr', 'ETB,Ethiopian Birr', 2, TRUE),
('Euro', 978, 'EUR', '€', 'Euro', 'EUR,Euro', 2, TRUE),
('Fiji Dollar', 242, 'FJD', 'FJD', 'Fiji Dollar', 'FJD,Fiji Dollar', 2, TRUE),
('Falkland Islands Pound', 238, 'FKP', 'FKP', 'Falkland Islands Pound', 'FKP,Falkland Islands Pound', 2, TRUE),
('Pound Sterling', 826, 'GBP', '£', 'Pound Sterling', 'GBP,Pound Sterling', 2, TRUE),
('Lari', 981, 'GEL', 'GEL', 'Lari', 'GEL,Lari', 2, TRUE),
('Ghana Cedi', 936, 'GHS', 'GHS', 'Ghana Cedi', 'GHS,Ghana Cedi', 2, TRUE),
('Gibraltar Pound', 292, 'GIP', 'GIP', 'Gibraltar Pound', 'GIP,Gibraltar Pound', 2, TRUE),
('Dalasi', 270, 'GMD', 'GMD', 'Dalasi', 'GMD,Dalasi', 2, TRUE),
('Guinean Franc', 324, 'GNF', 'GNF', 'Guinean Franc', 'GNF,Guinean Franc', 0, TRUE),
('Quetzal', 320, 'GTQ', 'GTQ', 'Quetzal', 'GTQ,Quetzal', 2, TRUE),
('Guyana Dollar', 328, 'GYD', 'GYD', 'Guyana Dollar', 'GYD,Guyana Dollar', 2, TRUE),
('Hong Kong Dollar', 344, 'HKD', 'HK$', 'Hong Kong Dollar', 'HKD,Hong Kong Dollar', 2, TRUE),
('Lempira', 340, 'HNL', 'HNL', 'Lempira', 'HNL,Lempira', 2, TRUE),
('Kuna', 191, 'HRK', 'HRK', 'Kuna', 'HRK,Kuna', 2, TRUE),
('Gourde', 332, 'HTG', 'HTG', 'Gourde', 'HTG,Gourde', 2, TRUE),
('Forint', 348, 'HUF', 'HUF', 'Forint', 'HUF,Forint', 2, TRUE),
('Rupiah', 360, 'IDR', 'IDR', 'Rupiah', 'IDR,Rupiah', 2, TRUE),
('New Israeli Sheqel', 376, 'ILS', '₪', 'New Israeli Sheqel', 'ILS,New Israeli Sheqel', 2, TRUE),
('Indian Rupee', 356, 'INR', '₹', 'Indian Rupee', 'INR,Indian Rupee', 2, TRUE),
('Iraqi Dinar', 368, 'IQD', 'IQD', 'Iraqi Dinar', 'IQD,Iraqi Dinar', 0, TRUE),
('Iranian Rial', 364, 'IRR', 'IRR', 'Iranian Rial', 'IRR,Iranian Rial', 0, TRUE),
('Iceland Krona', 352, 'ISK', 'ISK', 'Iceland Krona', 'ISK,Iceland Krona', 0, TRUE),
('Jamaican Dollar', 388, 'JMD', 'JMD', 'Jamaican Dollar', 'JMD,Jamaican Dollar', 2, TRUE),
('Jordanian Dinar', 400, 'JOD', 'JOD', 'Jordanian Dinar', 'JOD,Jordanian Dinar', 3, TRUE),
('Yen', 392, 'JPY', '¥', 'Yen', 'JPY,Yen', 0, TRUE),
('Kenyan Shilling', 404, 'KES', 'KES', 'Kenyan Shilling', 'KES,Kenyan Shilling', 2, TRUE),
('Som', 417, 'KGS', 'KGS', 'Som', 'KGS,Som', 2, TRUE),
('Riel', 116, 'KHR', 'KHR', 'Riel', 'KHR,Riel', 2, TRUE),
('Comorian Franc', 174, 'KMF', 'KMF', 'Comorian Franc', 'KMF,Comorian Franc', 0, TRUE),
('North Korean Won', 408, 'KPW', 'KPW', 'North Korean Won', 'KPW,North Korean Won', 0, TRUE),
('Won', 410, 'KRW', '₩', 'Won', 'KRW,Won', 0, TRUE),
('Kuwaiti Dinar', 414, 'KWD', 'KWD', 'Kuwaiti Dinar', 'KWD,Kuwaiti Dinar', 3, TRUE),
('Cayman Islands Dollar', 136, 'KYD', 'KYD', 'Cayman Islands Dollar', 'KYD,Cayman Islands Dollar', 2, TRUE),
('Tenge', 398, 'KZT', 'KZT', 'Tenge', 'KZT,Tenge', 2, TRUE),
('Lao Kip', 418, 'LAK', 'LAK', 'Lao Kip', 'LAK,Lao Kip', 0, TRUE),
('Lebanese Pound', 422, 'LBP', 'LBP', 'Lebanese Pound', 'LBP,Lebanese Pound', 0, TRUE),
('Sri Lanka Rupee', 144, 'LKR', 'LKR', 'Sri Lanka Rupee', 'LKR,Sri Lanka Rupee', 2, TRUE),
('Liberian Dollar', 430, 'LRD', 'LRD', 'Liberian Dollar', 'LRD,Liberian Dollar', 2, TRUE),
('Loti', 426, 'LSL', 'LSL', 'Loti', 'LSL,Loti', 2, TRUE),
('Libyan Dinar', 434, 'LYD', 'LYD', 'Libyan Dinar', 'LYD,Libyan Dinar', 3, TRUE),
('Moroccan Dirham', 504, 'MAD', 'MAD', 'Moroccan Dirham', 'MAD,Moroccan Dirham', 2, TRUE),
('Moldovan Leu', 498, 'MDL', 'MDL', 'Moldovan Leu', 'MDL,Moldovan Leu', 2, TRUE),
('Malagasy Ariary', 969, 'MGA', 'MGA', 'Malagasy Ariary', 'MGA,Malagasy Ariary', 0, TRUE),
('Denar', 807, 'MKD', 'MKD', 'Denar', 'MKD,Denar', 2, TRUE),
('Kyat', 104, 'MMK', 'MMK', 'Kyat', 'MMK,Kyat', 0, TRUE),
('Tugrik', 496, 'MNT', 'MNT', 'Tugrik', 'MNT,Tugrik', 2, TRUE),
('Pataca', 446, 'MOP', 'MOP', 'Pataca', 'MOP,Pataca', 2, TRUE),
('Ouguiya', 929, 'MRU', 'MRU', 'Ouguiya', 'MRU,Ouguiya', 2, TRUE),
('Mauritius Rupee', 480, 'MUR', 'MUR', 'Mauritius Rupee', 'MUR,Mauritius Rupee', 2, TRUE),
('Rufiyaa', 462, 'MVR', 'MVR', 'Rufiyaa', 'MVR,Rufiyaa', 2, TRUE),
('Malawi Kwacha', 454, 'MWK', 'MWK', 'Malawi Kwacha', 'MWK,Malawi Kwacha', 2, TRUE),
('Mexican Peso', 484, 'MXN', 'MX$', 'Mexican Peso', 'MXN,Mexican Peso', 2, TRUE),
('Mexican Unidad de Inversion (UDI)', 979, 'MXV', 'MXV', 'Mexican Unidad de Inversion (UDI)', 'MXV,Mexican Unidad de Inversion (UDI)', 2, TRUE),
('Malaysian Ringgit', 458, 'MYR', 'MYR', 'Malaysian Ringgit', 'MYR,Malaysian Ringgit', 2, TRUE),
('Mozambique Metical', 943, 'MZN', 'MZN', 'Mozambique Metical', 'MZN,Mozambique Metical', 2, TRUE),
('Namibia Dollar', 516, 'NAD', 'NAD', 'Namibia Dollar', 'NAD,Namibia Dollar', 2, TRUE),
('Naira', 566, 'NGN', 'NGN', 'Naira', 'NGN,Naira', 2, TRUE),
('Cordoba Oro', 558, 'NIO', 'NIO', 'Cordoba Oro', 'NIO,Cordoba Oro', 2, TRUE),
('Norwegian Krone', 578, 'NOK', 'NOK', 'Norwegian Krone', 'NOK,Norwegian Krone', 2, TRUE),
('Nepalese Rupee', 524, 'NPR', 'NPR', 'Nepalese Rupee', 'NPR,Nepalese Rupee', 2, TRUE),
('New Zealand Dollar', 554, 'NZD', 'NZ$', 'New Zealand Dollar', 'NZD,New Zealand Dollar', 2, TRUE),
('Rial Omani', 512, 'OMR', 'OMR', 'Rial Omani', 'OMR,Rial Omani', 3, TRUE),
('Balboa', 590, 'PAB', 'PAB', 'Balboa', 'PAB,Balboa', 2, TRUE),
('Sol', 604, 'PEN', 'PEN', 'Sol', 'PEN,Sol', 2, TRUE),
('Kina', 598, 'PGK', 'PGK', 'Kina', 'PGK,Kina', 2, TRUE),
('Philippine Peso', 608, 'PHP', '₱', 'Philippine Peso', 'PHP,Philippine Peso', 2, TRUE),
('Pakistan Rupee', 586, 'PKR', 'PKR', 'Pakistan Rupee', 'PKR,Pakistan Rupee', 2, TRUE),
('Zloty', 985, 'PLN', 'PLN', 'Zloty', 'PLN,Zloty', 2, TRUE),
('Guarani', 600, 'PYG', 'PYG', 'Guarani', 'PYG,Guarani', 0, TRUE),
('Qatari Rial', 634, 'QAR', 'QAR', 'Qatari Rial', 'QAR,Qatari Rial', 2, TRUE),
('Romanian Leu', 946, 'RON', 'RON', 'Romanian Leu', 'RON,Romanian Leu', 2, TRUE),
('Serbian Dinar', 941, 'RSD', 'RSD', 'Serbian Dinar', 'RSD,Serbian Dinar', 0, TRUE),
('Russian Ruble', 643, 'RUB', 'RUB', 'Russian Ruble', 'RUB,Russian Ruble', 2, TRUE),
('Rwanda Franc', 646, 'RWF', 'RWF', 'Rwanda Franc', 'RWF,Rwanda Franc', 0, TRUE),
('Saudi Riyal', 682, 'SAR', 'SAR', 'Saudi Riyal', 'SAR,Saudi Riyal', 2, TRUE),
('Solomon Islands Dollar', 90, 'SBD', 'SBD', 'Solomon Islands Dollar', 'SBD,Solomon Islands Dollar', 2, TRUE),
('Seychelles Rupee', 690, 'SCR', 'SCR', 'Seychelles Rupee', 'SCR,Seychelles Rupee', 2, TRUE),
('Sudanese Pound', 938, 'SDG', 'SDG', 'Sudanese Pound', 'SDG,Sudanese Pound', 2, TRUE),
('Swedish Krona', 752, 'SEK', 'SEK', 'Swedish Krona', 'SEK,Swedish Krona', 2, TRUE),
('Singapore Dollar', 702, 'SGD', 'SGD', 'Singapore Dollar', 'SGD,Singapore Dollar', 2, TRUE),
('Saint Helena Pound', 654, 'SHP', 'SHP', 'Saint Helena Pound', 'SHP,Saint Helena Pound', 2, TRUE),
('Leone', 925, 'SLE', 'SLE', 'Leone', 'SLE,Leone', 2, TRUE),
('Leone', 694, 'SLL', 'SLL', 'Leone', 'SLL,Leone', 0, TRUE),
('Somali Shilling', 706, 'SOS', 'SOS', 'Somali Shilling', 'SOS,Somali Shilling', 0, TRUE),
('Surinam Dollar', 968, 'SRD', 'SRD', 'Surinam Dollar', 'SRD,Surinam Dollar', 2, TRUE),
('South Sudanese Pound', 728, 'SSP', 'SSP', 'South Sudanese Pound', 'SSP,South Sudanese Pound', 2, TRUE),
('Dobra', 930, 'STN', 'STN', 'Dobra', 'STN,Dobra', 2, TRUE),
('El Salvador Colon', 222, 'SVC', 'SVC', 'El Salvador Colon', 'SVC,El Salvador Colon', 2, TRUE),
('Syrian Pound', 760, 'SYP', 'SYP', 'Syrian Pound', 'SYP,Syrian Pound', 0, TRUE),
('Lilangeni', 748, 'SZL', 'SZL', 'Lilangeni', 'SZL,Lilangeni', 2, TRUE),
('Baht', 764, 'THB', 'THB', 'Baht', 'THB,Baht', 2, TRUE),
('Somoni', 972, 'TJS', 'TJS', 'Somoni', 'TJS,Somoni', 2, TRUE),
('Turkmenistan New Manat', 934, 'TMT', 'TMT', 'Turkmenistan New Manat', 'TMT,Turkmenistan New Manat', 2, TRUE),
('Tunisian Dinar', 788, 'TND', 'TND', 'Tunisian Dinar', 'TND,Tunisian Dinar', 3, TRUE),
('Pa’anga', 776, 'TOP', 'TOP', 'Pa’anga', 'TOP,Pa’anga', 2, TRUE),
('Turkish Lira', 949, 'TRY', 'TRY', 'Turkish Lira', 'TRY,Turkish Lira', 2, TRUE),
('Trinidad and Tobago Dollar', 780, 'TTD', 'TTD', 'Trinidad and Tobago Dollar', 'TTD,Trinidad and Tobago Dollar', 2, TRUE),
('New Taiwan Dollar', 901, 'TWD', 'NT$', 'New Taiwan Dollar', 'TWD,New Taiwan Dollar', 2, TRUE),
('Tanzanian Shilling', 834, 'TZS', 'TZS', 'Tanzanian Shilling', 'TZS,Tanzanian Shilling', 2, TRUE),
('Hryvnia', 980, 'UAH', 'UAH', 'Hryvnia', 'UAH,Hryvnia', 2, TRUE),
('Uganda Shilling', 800, 'UGX', 'UGX', 'Uganda Shilling', 'UGX,Uganda Shilling', 0, TRUE),
('US Dollar', 840, 'USD', '$', 'US Dollar', 'USD,US Dollar', 2, TRUE),
('US Dollar (Next day)', 997, 'USN', 'USN', 'US Dollar (Next day)', 'USN,US Dollar (Next day)', 2, TRUE),
('Uruguay Peso en Unidades Indexadas (UI)', 940, 'UYI', 'UYI', 'Uruguay Peso en Unidades Indexadas (UI)', 'UYI,Uruguay Peso en Unidades Indexadas (UI)', 0, TRUE),
('Peso Uruguayo', 858, 'UYU', 'UYU', 'Peso Uruguayo', 'UYU,Peso Uruguayo', 2, TRUE),
('Unidad Previsional', 927, 'UYW', 'UYW', 'Unidad Previsional', 'UYW,Unidad Previsional', 4, TRUE),
('Uzbekistan Sum', 860, 'UZS', 'UZS', 'Uzbekistan Sum', 'UZS,Uzbekistan Sum', 2, TRUE),
('Bolívar Soberano', 926, 'VED', 'VED', 'Bolívar Soberano', 'VED,Bolívar Soberano', 2, TRUE),
('Bolívar Soberano', 928, 'VES', 'VES', 'Bolívar Soberano', 'VES,Bolívar Soberano', 2, TRUE),
('Dong', 704, 'VND', '₫', 'Dong', 'VND,Dong', 0, TRUE),
('Vatu', 548, 'VUV', 'VUV', 'Vatu', 'VUV,Vatu', 0, TRUE),
('Tala', 882, 'WST', 'WST', 'Tala', 'WST,Tala', 2, TRUE),
('CFA Franc BEAC', 950, 'XAF', 'FCFA', 'CFA Franc BEAC', 'XAF,CFA Franc BEAC', 0, TRUE),
('Silver', 961, 'XAG', 'XAG', 'Silver', 'XAG,Silver', 2, TRUE),
('Gold', 959, 'XAU', 'XAU', 'Gold', 'XAU,Gold', 2, TRUE),
('Bond Markets Unit European Composite Unit (EURCO)', 955, 'XBA', 'XBA', 'Bond Markets Unit European Composite Unit (EURCO)', 'XBA,Bond Markets Unit European Composite Unit (EURCO)', 2, TRUE),
('Bond Markets Unit European Monetary Unit (E.M.U.-6)', 956, 'XBB', 'XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'XBB,Bond Markets Unit European Monetary Unit (E.M.U.-6)', 2, TRUE),
('Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 957, 'XBC', 'XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'XBC,Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 2, TRUE),
('Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 958, 'XBD', 'XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'XBD,Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 2, TRUE),
('East Caribbean Dollar', 951, 'XCD', 'EC$', 'East Caribbean Dollar', 'XCD,East Caribbean Dollar', 2, TRUE),
('SDR (Special Drawing Right)', 960, 'XDR', 'XDR', 'SDR (Special Drawing Right)', 'XDR,SDR (Special Drawing Right)', 2, TRUE),
('CFA Franc BCEAO', 952, 'XOF', 'F CFA', 'CFA Franc BCEAO', 'XOF,CFA Franc BCEAO', 0, TRUE),
('Palladium', 964, 'XPD', 'XPD', 'Palladium', 'XPD,Palladium', 2, TRUE),
('CFP Franc', 953, 'XPF', 'CFPF', 'CFP Franc', 'XPF,CFP Franc', 0, TRUE),
('Platinum', 962, 'XPT', 'XPT', 'Platinum', 'XPT,Platinum', 2, TRUE),
('Sucre', 994, 'XSU', 'XSU', 'Sucre', 'XSU,Sucre', 2, TRUE),
('Codes specifically reserved for testing purposes', 963, 'XTS', 'XTS', 'Codes specifically reserved for testing purposes', 'XTS,Codes specifically reserved for testing purposes', 2, TRUE),
('ADB Unit of Account', 965, 'XUA', 'XUA', 'ADB Unit of Account', 'XUA,ADB Unit of Account', 2, TRUE),
('The codes assigned for transactions where no currency is involved', 999, 'XXX', '¤', 'The codes assigned for transactions where no currency is involved', 'XXX,The codes assigned for transactions where no currency is involved', 2, TRUE),
('Yemeni Rial', 886, 'YER', 'YER', 'Yemeni Rial', 'YER,Yemeni Rial', 0, TRUE),
('Rand', 710, 'ZAR', 'ZAR', 'Rand', 'ZAR,Rand', 2, TRUE),
('Zambian Kwacha', 967, 'ZMW', 'ZMW', 'Zambian Kwacha', 'ZMW,Zambian Kwacha', 2, TRUE),
('Zimbabwe Dollar', 932, 'ZWL', 'ZWL', 'Zimbabwe Dollar', 'ZWL,Zimbabwe Dollar', 2, TRUE);

COMMIT;

-- Total rows: 181