CREATE ROLE IF NOT EXISTS db_access_readyonly NOLOGIN;
CREATE ROLE IF NOT EXISTS db_access_readwrite NOLOGIN;
CREATE ROLE IF NOT EXISTS db_access_ddl NOLOGIN;
CREATE ROLE IF NOT EXISTS db_access_execute NOLOGIN;
CREATE ROLE IF NOT EXISTS db_access_admin NOLOGIN;
CREATE ROLE IF NOT EXISTS db_access_owner NOLOGIN;