CREATE OR REPLACE FUNCTION PUBLIC.GET_ACTION_USER_ID()
    RETURNS TEXT
    LANGUAGE PLPGSQL
AS $FUNCTION$
BEGIN
  RETURN  COALESCE(
        CURRENT_SETTING('USER.NAME',TRUE),
        SESSION_USER
    );
END;
$FUNCTION$