CREATE OR REPLACE FUNCTION GET_JSON_DIFF(OLD_DATA JSONB, NEW_DATA JSONB)
    RETURNS JSONB
    LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    _DIFF_DATA JSONB = NEW_DATA;
    _EXISTING_RECORD RECORD;
BEGIN
    IF OLD_DATA IS NULL OR NEW_DATA IS NULL THEN
        RETURN COALESCE(NEW_DATA,'{}'::JSONB);
    END IF;
    
    FOR _EXISTING_RECORD IN
        SELECT * FROM JSONB_EACH_TEXT(OLD_DATA)
    LOOP
        IF _DIFF_DATA ? _EXISTING_RECORD.KEY THEN
            IF _DIFF_DATA ->> _EXISTING_RECORD.KEY = _EXISTING_RECORD.VALUE THEN
                _DIFF_DATA = _DIFF_DATA - _EXISTING_RECORD.KEY;
            END IF;
        END IF;
    END LOOP;

RETURN _DIFF_DATA;
END;
$FUNCTION$;