CREATE OR REPLACE FUNCTION GET_ACTION_USER_NAME()
    RETURNS TEXT
    LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
    _USER_ID TEXT;
    _USER_NAME TEXT;
BEGIN
    _USER_ID =   COALESCE(CURRENT_SETTING('USER.NAME',TRUE),SESSION_USER);
    
    SELECT u.user_name INTO _USER_NAME FROM public.app_users u WHERE u.user_id = v_user_id;

    RETURN COALESCE(_USER_NAME,_USER_ID,'ADMIN USER');
END;
$FUNCTION$