-- dropping iso_currency, iso_currency_audit_log tables & iso_currency_id_seq, iso_currency_audit_log_id_seq sequences
drop table if exists public.iso_currency;
drop table if exists public.iso_currency_audit_log;
drop sequence if exists public.iso_currency_id_seq;
drop sequence if exists public.iso_currency_audit_log_id_seq;

--creating the sequence for the iso_currency_id
create sequence public.iso_currency_id_seq
increment by 1
minvalue 1
maxvalue 9223372036854775807
start 1
cache 1
no cycle;


--script for creating the iso_currency table
create table public.iso_currency (
id int8 not null generated by default as identity (increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle), 
iso_name text not null,
iso_numeric_code int4 not null,
iso_3_code text not null,
currency_symbol text not null,
preferred_name text not null,
alternative_names text not null,
decimal_places int4 not null,
is_enabled bool not null,

constraint iso_currency_pkey primary key (id)
);

create unique index currency_iso_3_code_idx on public.iso_currency using btree (iso_3_code);
create unique index currency_iso_name_idx on public.iso_currency using btree (iso_name);
create unique index currency_iso_numeric_code_idx on public.iso_currency using btree (iso_numeric_code);
create unique index currency_preferred_name_idx on public.iso_currency using btree (preferred_name);


--creating the sequence for the audit_log_id
create sequence public.iso_currency_audit_log_id_seq
increment by 1
minvalue 1
maxvalue 9223372036854775807
start 1
cache 1
no cycle;


--script for creating the iso_currency_audit_log table
create table public.iso_currency_audit_log(
id int8 not null generated by default as identity (increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle),
iso_currency_id int8 not null,
transcation_id int8 not null,
action bpchar not null,
row_data jsonb not null,
action_user_id text not null,
action_user_name text not null,
action_timestamp timestamp not null,
statement_timestamp timestamp not null,

constraint iso_currency_audit_pkey primary key (id)

);

create index iso_currency_audit_log_currency_id_idx on public.iso_currency_audit_log using btree (iso_currency_id);


--function for creating the iso_currency_audit_record
create or replace function public.create_iso_currency_audit_record()
  returns trigger 
  language plpgsql
as $function$
declare
_iso_currency_id bigint;
_transcation_id bigint;
_action char(1);
_row_data jsonb;
_action_user_id text;
_action_user_name text;
_action_time_stamp timestamp;
_statement_time_stamp timestamp;
begin
if tg_when <> 'after' then 
raise exception 'the create currency audit record function can only be used as an after trigger';
end if;

_iso_currency_id = coalesce(old.id, new.id);
_transcation_id = txid_current();
_action = substring (tg_op, 1 , 1);
_action_user_id = get_action_user_id();
_action_user_name = get_action_user_name();
_action_time_stamp = current_timestamp;
_statement_time_stamp = statement_timestamp();

if _action = 'i' then
   _row_data = row_to_json(new);
elsif _action = 'u' then
_row_data = get_json_diff(row_to_json (new):: jsonb, row_to_json (old) ::jsonb);
elsif _action = 'd' then
_row_data = row_to_json (old);
else
raise exception 'invalid action % for create currency_audit_record function.', tg_op;
end if;

insert into public.iso_currency_audit_log(
iso_currency_id, transcation_id, action, row_data, action_user_id, action_user_name, action_timestamp,statement_timestamp
)
values (
_iso_currency_id, _transcation_id, _action, _row_data, _action_user_id, _action_user_name, _action_time_stamp, _statement_time_stamp
);
return null;

end;
$function$
;


--trigger for iso_currency_audit
create trigger iso_currency_audit_trigger after
insert 
or
update
or
delete
on
public.iso_currency for each row execute function create_iso_currency_audit_record();
