
-- dropping iso_country, iso_country_audit_log tables & iso_country_id_seq, iso_country_audit_log_id_seq sequences
drop table if exists public.iso_country;
drop table if exists public.iso_country_audit_log;
drop sequence if exists public.iso_country_id_seq;
drop sequence if exists public.iso_country_audit_log_id_seq;

--creating the sequence for the iso_country_id
create sequence public.iso_country_id_seq
	increment by 1
	minvalue 1
	maxvalue 9223372036854775807
	start 1
	cache 1
	no cycle;
	

--script for creating the iso_country table
create table public.iso_country (
	id int8 not null generated by default as identity (increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle), 
	iso_name text not null,
	iso_numeric_code int4 not null,
	iso_2_code text not null,
	iso_3_code text not null,
	preferred_name text not null,
	alternative_names text not null,
	risk_rating text not null,
	is_enabled bool not null,
	
	constraint iso_country_pkey primary key (id)
	constraint chk_iso_country_risk_rating
    check (risk_rating in (
    'low',
    'medium',
    'high',
    'prohibited',
    'sanctioned'
))
);

create unique index country_iso_2_code_idx on public.iso_country using btree (iso_2_code);
create unique index country_iso_3_code_idx on public.iso_country using btree (iso_3_code);
create unique index country_iso_name_idx on public.iso_country using btree (iso_name);
create unique index country_iso_numeric_code_idx on public.iso_country using btree (iso_numeric_code);
create unique index country_preferred_name_idx on public.iso_country using btree (preferred_name);


--creating the sequence for the audit_log_id
create sequence public.iso_country_audit_log_id_seq
	increment by 1
	minvalue 1
	maxvalue 9223372036854775807
	start 1
	cache 1
	no cycle;
		
	
--script for creating the iso_country_audit_log table
create table public.iso_country_audit_log(
	id int8 not null generated by default as identity (increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle),
	iso_country_id int8 not null,
	transcation_id int8 not null,
	action bpchar not null,
	row_data jsonb not null,
	action_user_id text not null,
	action_user_name text not null,
	action_timestamp timestamp not null,
	statement_timestamp timestamp not null,
	
	constraint iso_country_audit_pkey primary key (id)	
	
);

create index iso_country_audit_log_country_id_idx on public.iso_country_audit_log using btree (iso_country_id);


--function for creating the iso_country_audit_record
create or replace function public.create_iso_country_audit_record()
  returns trigger 
  language plpgsql
as $function$
declare
	_iso_country_id bigint;
	_transcation_id bigint;
	_action char(1);
	_row_data jsonb;
	_action_user_id text;
	_action_user_name text;
	_action_time_stamp timestamp;
	_statement_time_stamp timestamp;
begin
	if tg_when <> 'after' then 
		raise exception 'the create country audit record function can only be used as an after trigger';
	end if;

	_iso_country_id = coalesce(old.id, new.id);
	_transcation_id = txid_current();
	_action = substring (tg_op, 1 , 1);
	_action_user_id = get_action_user_id();
	_action_user_name = get_action_user_name();
	_action_time_stamp = current_timestamp;
	_statement_time_stamp = statement_timestamp();

	if _action = 'i' then
   			_row_data = row_to_json(new);
	elsif _action = 'u' then
			_row_data = get_json_diff(row_to_json (new):: jsonb, row_to_json (old) ::jsonb);
	elsif _action = 'd' then
			_row_data = row_to_json (old);
	else
			raise exception 'invalid action % for create country_audit_record function.', tg_op;
	end if;

	insert into public.iso_country_audit_log(
		iso_country_id, transcation_id, action, row_data, action_user_id, action_user_name, action_timestamp,statement_timestamp
	)
	values (
		_iso_country_id, _transcation_id, _action, _row_data, _action_user_id, _action_user_name, _action_time_stamp, _statement_time_stamp
	);
	return null;

end;
$function$
;


--trigger for iso_country_audit
create trigger iso_country_audit_trigger after
insert 
	or
update
	or
delete
	on
	public.iso_country for each row execute function create_iso_country_audit_record();